# Generated by Django 3.2.5 on 2021-07-23 15:08

from django.db import migrations, models
import django.db.models.deletion
import showcase.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Glider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=10)),
                ('year', showcase.fields.Year()),
                ('gliderWeight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.maker')),
            ],
        ),
    ]
