# Generated by Django 3.2.5 on 2021-07-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glider',
            name='gliderImage',
            field=models.ImageField(default=None, upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>'),
        ),
    ]
