# Generated by Django 3.2.5 on 2021-07-31 16:48

from django.db import migrations, models
import showcase.models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_alter_glider_gliderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glider',
            name='gliderImage',
            field=models.ImageField(default=None, upload_to=showcase.models.get_upload_glider_image),
        ),
    ]
