# Generated by Django 3.2.5 on 2021-08-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20210807_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glider',
            name='gliderWeight',
        ),
    ]
