# Generated by Django 3.2.5 on 2021-08-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210807_0828'),
        ('showcase', '0003_remove_glider_gliderweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='textIntro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GliderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('glider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glider_review', to='showcase.glider')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='members.person')),
            ],
        ),
    ]
