# Generated by Django 3.2.5 on 2021-08-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_auto_20210807_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
