# Generated by Django 3.2.5 on 2021-08-07 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0005_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gliderreview',
            name='person',
        ),
        migrations.AddField(
            model_name='gliderreview',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='members.user'),
            preserve_default=False,
        ),
    ]
