# Generated by Django 3.2.5 on 2021-08-09 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gliderreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='gliderreview',
            constraint=models.UniqueConstraint(fields=('user', 'glider'), name='a user can have only one review per glider'),
        ),
    ]
