# Generated by Django 3.2.5 on 2021-08-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparetool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareitems',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
