# Generated by Django 3.2.5 on 2021-08-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
